// 

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "GameplayTagContainer.h"
#include "SussContext.h"
#include "UObject/Object.h"
#include "SussInputProvider.generated.h"



/**
 * An input provider supplies a float input value to a considerations, which is determined at runtime, and identified by an input tag.
 * Every input provider must:
 * 1) Define a gameplay tag representing the input, which must begin with "Suss.Input".
 *	  You can do this either using UE_DEFINE_GAMEPLAY_TAG_STATIC or adding it to tag INI files
 * 2) Create a subclass of USussInputProvider which defines & implements this input
 * 3) Register this class with USussEngineSubsystem::RegisterInputProvider (can be done in Settings, or by placing BPs
 *    in a folder that settings looks in.
 *
 * Inputs are always a single value based on a given context. Contexts are generated by Queries, which are provided
 * separately. 
 *
 * Input providers themselves are stateless, which is why only the class needs to be registered, SUSS uses the CDO.
 */
UCLASS(Blueprintable, Abstract)
class SUSS_API USussInputProvider : public UPrimaryDataAsset
{
	GENERATED_BODY()
protected:
	/// The tag which identifies the input which this provider is supplying
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, meta=(Categories="Suss.Input"))
	FGameplayTag InputTag;
	
public:

	USussInputProvider() {}
	
	const FGameplayTag& GetInputTag() const { return InputTag; }

	
	/// Evaluate the input given a context
	/// Also used to resolve parameters to queries and other inputs, in which case context is solely the Self reference
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable)	
	float Evaluate(const class USussBrainComponent* Brain, const FSussContext& Context, const TMap<FName, FSussParameter>& Parameters) const;
};
